# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_GUI.ui'
##
## Created by: Qt User Interface Compiler version 6.6.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QApplication, QFrame, QGridLayout,
    QHeaderView, QLineEdit, QMainWindow, QPushButton,
    QSizePolicy, QSpacerItem, QStatusBar, QTableWidget,
    QTableWidgetItem, QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 427)
        MainWindow.setMinimumSize(QSize(500, 0))
        font = QFont()
        font.setFamilies([u"Tahoma"])
        font.setPointSize(12)
        MainWindow.setFont(font)
        MainWindow.setWindowTitle(u"CSV EDITOR")
        icon = QIcon()
        icon.addFile(u"csv.ico", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
#if QT_CONFIG(tooltip)
        MainWindow.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        MainWindow.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        MainWindow.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        MainWindow.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        MainWindow.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        MainWindow.setWindowFilePath(u"")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
#if QT_CONFIG(tooltip)
        self.centralwidget.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.centralwidget.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.centralwidget.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.centralwidget.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.centralwidget.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        self.gridLayout_2 = QGridLayout(self.centralwidget)
        self.gridLayout_2.setSpacing(10)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_2.setContentsMargins(10, 10, 10, 10)
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setFrameShape(QFrame.NoFrame)
        self.frame.setFrameShadow(QFrame.Raised)
        self.gridLayout = QGridLayout(self.frame)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.btn_load = QPushButton(self.frame)
        self.btn_load.setObjectName(u"btn_load")
        self.btn_load.setMinimumSize(QSize(65, 40))
        self.btn_load.setMaximumSize(QSize(65, 40))
        font1 = QFont()
        font1.setFamilies([u"Roboto Black"])
        font1.setPointSize(14)
        font1.setBold(True)
        self.btn_load.setFont(font1)
#if QT_CONFIG(tooltip)
        self.btn_load.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.btn_load.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.btn_load.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.btn_load.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.btn_load.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        self.btn_load.setText(u"")
#if QT_CONFIG(shortcut)
        self.btn_load.setShortcut(u"")
#endif // QT_CONFIG(shortcut)

        self.gridLayout.addWidget(self.btn_load, 0, 1, 1, 1)

        self.btn_save = QPushButton(self.frame)
        self.btn_save.setObjectName(u"btn_save")
        self.btn_save.setMinimumSize(QSize(65, 40))
        self.btn_save.setMaximumSize(QSize(65, 40))
        self.btn_save.setFont(font1)
#if QT_CONFIG(tooltip)
        self.btn_save.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.btn_save.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.btn_save.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.btn_save.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.btn_save.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        self.btn_save.setText(u"")
#if QT_CONFIG(shortcut)
        self.btn_save.setShortcut(u"")
#endif // QT_CONFIG(shortcut)

        self.gridLayout.addWidget(self.btn_save, 0, 2, 1, 1)

        self.tx_filename = QLineEdit(self.frame)
        self.tx_filename.setObjectName(u"tx_filename")
        self.tx_filename.setMinimumSize(QSize(0, 40))
        self.tx_filename.setMaximumSize(QSize(16777215, 40))
        font2 = QFont()
        font2.setFamilies([u"Consolas"])
        font2.setPointSize(12)
        self.tx_filename.setFont(font2)
        self.tx_filename.setAcceptDrops(False)
#if QT_CONFIG(whatsthis)
        self.tx_filename.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.tx_filename.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.tx_filename.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        self.tx_filename.setText(u"")
        self.tx_filename.setMaxLength(100)
        self.tx_filename.setFrame(True)
        self.tx_filename.setPlaceholderText(u"")

        self.gridLayout.addWidget(self.tx_filename, 0, 0, 1, 1)


        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 2)

        self.tbl_data = QTableWidget(self.centralwidget)
        self.tbl_data.setObjectName(u"tbl_data")
        self.tbl_data.setFont(font2)
#if QT_CONFIG(tooltip)
        self.tbl_data.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.tbl_data.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.tbl_data.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.tbl_data.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.tbl_data.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        self.tbl_data.setDragEnabled(True)
        self.tbl_data.setDragDropMode(QAbstractItemView.DragDrop)
        self.tbl_data.setAlternatingRowColors(True)
        self.tbl_data.setShowGrid(True)
        self.tbl_data.setGridStyle(Qt.SolidLine)
        self.tbl_data.setSortingEnabled(True)
        self.tbl_data.horizontalHeader().setVisible(True)
        self.tbl_data.horizontalHeader().setCascadingSectionResizes(False)
        self.tbl_data.horizontalHeader().setMinimumSectionSize(40)
        self.tbl_data.horizontalHeader().setDefaultSectionSize(200)
        self.tbl_data.verticalHeader().setVisible(False)
        self.tbl_data.verticalHeader().setMinimumSectionSize(30)
        self.tbl_data.verticalHeader().setDefaultSectionSize(40)
        self.tbl_data.verticalHeader().setHighlightSections(False)

        self.gridLayout_2.addWidget(self.tbl_data, 1, 0, 1, 1)

        self.frame_2 = QFrame(self.centralwidget)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setFrameShape(QFrame.NoFrame)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.verticalLayout = QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, -1, 0, -1)
        self.btn_fields = QPushButton(self.frame_2)
        self.btn_fields.setObjectName(u"btn_fields")
        self.btn_fields.setMinimumSize(QSize(140, 50))
        self.btn_fields.setMaximumSize(QSize(140, 50))
        font3 = QFont()
        font3.setFamilies([u"Roboto Black"])
        font3.setPointSize(12)
        font3.setBold(True)
        self.btn_fields.setFont(font3)
#if QT_CONFIG(tooltip)
        self.btn_fields.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.btn_fields.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.btn_fields.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.btn_fields.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.btn_fields.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        self.btn_fields.setText(u"FIELDS")
#if QT_CONFIG(shortcut)
        self.btn_fields.setShortcut(u"")
#endif // QT_CONFIG(shortcut)

        self.verticalLayout.addWidget(self.btn_fields)

        self.btn_add = QPushButton(self.frame_2)
        self.btn_add.setObjectName(u"btn_add")
        self.btn_add.setMinimumSize(QSize(140, 50))
        self.btn_add.setMaximumSize(QSize(140, 50))
        self.btn_add.setFont(font3)
#if QT_CONFIG(tooltip)
        self.btn_add.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.btn_add.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.btn_add.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.btn_add.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.btn_add.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        self.btn_add.setText(u"ADD")
#if QT_CONFIG(shortcut)
        self.btn_add.setShortcut(u"")
#endif // QT_CONFIG(shortcut)

        self.verticalLayout.addWidget(self.btn_add)

        self.btn_duplicate = QPushButton(self.frame_2)
        self.btn_duplicate.setObjectName(u"btn_duplicate")
        self.btn_duplicate.setMinimumSize(QSize(140, 50))
        self.btn_duplicate.setMaximumSize(QSize(140, 50))
        self.btn_duplicate.setFont(font3)
#if QT_CONFIG(tooltip)
        self.btn_duplicate.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.btn_duplicate.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.btn_duplicate.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.btn_duplicate.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.btn_duplicate.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        self.btn_duplicate.setText(u"x2")
#if QT_CONFIG(shortcut)
        self.btn_duplicate.setShortcut(u"")
#endif // QT_CONFIG(shortcut)

        self.verticalLayout.addWidget(self.btn_duplicate)

        self.btn_del = QPushButton(self.frame_2)
        self.btn_del.setObjectName(u"btn_del")
        self.btn_del.setMinimumSize(QSize(140, 50))
        self.btn_del.setMaximumSize(QSize(140, 50))
        self.btn_del.setFont(font3)
#if QT_CONFIG(tooltip)
        self.btn_del.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.btn_del.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.btn_del.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.btn_del.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.btn_del.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        self.btn_del.setText(u"DEL")
#if QT_CONFIG(shortcut)
        self.btn_del.setShortcut(u"")
#endif // QT_CONFIG(shortcut)

        self.verticalLayout.addWidget(self.btn_del)

        self.verticalSpacer = QSpacerItem(20, 183, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.verticalLayout.addItem(self.verticalSpacer)


        self.gridLayout_2.addWidget(self.frame_2, 1, 1, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        font4 = QFont()
        font4.setFamilies([u"Tahoma"])
        font4.setPointSize(8)
        self.statusbar.setFont(font4)
#if QT_CONFIG(tooltip)
        self.statusbar.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.statusbar.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.statusbar.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.statusbar.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.statusbar.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        pass
    # retranslateUi

